version: "3.9"

services:

  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    restart: unless-stopped
    entrypoint: headscale serve
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    ports:
      - "3478:3478"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`headscale.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=cloudflare"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"
        
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "headscale", "nodes", "list" ]
      interval: 30s
      timeout: 10s
      retries: 3

  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    environment:
      - TZ=Europe/Paris
      - HS_SERVER=https://headscale.ozeliurs.com
      - DOMAIN_NAME=https://headscale-ui.ozeliurs.com/
    env_file:
      - .headscale-ui.env
    volumes:
      - ./headscale-ui:/data
      - ./headscale/config:/etc/headscale:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale-webui.rule=Host(`headscale-ui.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.headscale-webui.entrypoints=websecure"
      - "traefik.http.routers.headscale-webui.tls=true"
      - "traefik.http.routers.headscale-webui.tls.certresolver=cloudflare"
      - "traefik.http.services.headscale-webui.loadbalancer.server.port=5000"
        
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      headscale:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  traefik:
    external: true
